In [1]:
2+5

7

In [3]:
for i in range(10):
    print(i+1)

1
2
3
4
5
6
7
8
9
10


In [5]:
import numpy as np

In [11]:
a = [0,1,2,3,4,5,6]
for i in a:
    print(i)

0
1
2
3
4
5
6


In [7]:
range(5)

range(0, 5)

In [14]:
p = np.arange(6)

In [21]:
for i in p:
    print(p)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


# Creating List

In [28]:
list = []

for i in range(10):
    list.append(i)
    print(list)


[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [29]:
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]